curent_department = 'Department of Agriculture'
main_url = "https://itdashboard.gov/"


# данные для теста
list_deps = [
    {'name': 'Department of Agriculture', 'sum': '$2.7B', 'href': 'https://itdashboard.gov/drupal/summary/005'}, 
    {'name': 'Department of Commerce', 'sum': '$2.8B', 'href': 'https://itdashboard.gov/drupal/summary/006'}, 
    {'name': 'Department of Defense', 'sum': '$36B', 'href': 'https://itdashboard.gov/drupal/summary/007'}, 
    {'name': 'Department of Health and Human Services', 'sum': '$7.0B', 'href': 'https://itdashboard.gov/drupal/summary/009'}, 
    {'name': 'Department of the Interior', 'sum': '$1.5B', 'href': 'https://itdashboard.gov/drupal/summary/010'}, 
    {'name': 'Department of Justice', 'sum': '$3.1B', 'href': 'https://itdashboard.gov/drupal/summary/011'}, 
    {'name': 'Department of Labor', 'sum': '$819M', 'href': 'https://itdashboard.gov/drupal/summary/012'}, 
    {'name': 'Department of State', 'sum': '$2.6B', 'href': 'https://itdashboard.gov/drupal/summary/014'}, 
    {'name': 'Department of the Treasury', 'sum': '$5.4B', 'href': 'https://itdashboard.gov/drupal/summary/015'}, 
    {'name': 'Social Security Administration', 'sum': '$2.0B', 'href': 'https://itdashboard.gov/drupal/summary/016'}, 
    {'name': 'Department of Education', 'sum': '$1.0B', 'href': 'https://itdashboard.gov/drupal/summary/018'}, 
    {'name': 'Department of Energy', 'sum': '$3.1B', 'href': 'https://itdashboard.gov/drupal/summary/019'}, 
    {'name': 'Environmental Protection Agency', 'sum': '$385M', 'href': 'https://itdashboard.gov/drupal/summary/020'}, 
    {'name': 'Department of Transportation', 'sum': '$3.5B', 'href': 'https://itdashboard.gov/drupal/summary/021'}, 
    {'name': 'General Services Administration', 'sum': '$765M', 'href': 'https://itdashboard.gov/drupal/summary/023'}, 
    {'name': 'Department of Homeland Security', 'sum': '$7.4B', 'href': 'https://itdashboard.gov/drupal/summary/024'}, 
    {'name': 'Department of Housing and Urban Development', 'sum': '$447M', 'href': 'https://itdashboard.gov/drupal/summary/025'}, 
    {'name': 'National Aeronautics and Space Administration', 'sum': '$2.2B', 'href': 'https://itdashboard.gov/drupal/summary/026'}, 
    {'name': 'Office of Personnel Management', 'sum': '$125M', 'href': 'https://itdashboard.gov/drupal/summary/027'}, 
    {'name': 'Small Business Administration', 'sum': '$129M', 'href': 'https://itdashboard.gov/drupal/summary/028'}, 
    {'name': 'Department of Veterans Affairs', 'sum': '$9.1B', 'href': 'https://itdashboard.gov/drupal/summary/029'}, 
    {'name': 'U.S. Agency for International Development', 'sum': '$256M', 'href': 'https://itdashboard.gov/drupal/summary/184'}, 
    {'name': 'U.S. Army Corps of Engineers', 'sum': '$275M', 'href': 'https://itdashboard.gov/drupal/summary/202'}, 
    {'name': 'National Archives and Records Administration', 'sum': '$99.9M', 'href': 'https://itdashboard.gov/drupal/summary/393'}, 
    {'name': 'National Science Foundation', 'sum': '$136M', 'href': 'https://itdashboard.gov/drupal/summary/422'}, 
    {'name': 'Nuclear Regulatory Commission', 'sum': '$141M', 'href': 'https://itdashboard.gov/drupal/summary/429'}
    ]

table_data = [
    {'UII': '005-000000018', 'Bureau': 'Agricultural Marketing Service', 'Investment Title': 'MRP-AMS-Web-Based Supply Chain Management (WBSCM)', 'Total FY2021 Spending ($M)': '$31.642', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '6'}, 
    {'UII': '005-000000035', 'Bureau': 'Office of Chief Information Officer', 'Investment Title': 'SO-OCIO-DISC-AgLearn', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '5', '# of Projects': '6'}, 
    {'UII': '005-000000039', 'Bureau': 'Office of the Secretary', 'Investment Title': 'DA-OCP-Integrated Acquisition System (IAS)', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '5', '# of Projects': '18'}, 
    {'UII': '005-000000042', 'Bureau': 'Food and Nutrition Service', 'Investment Title': 'FNCS-FNS-Anti-Fraud Locator Using EBT Retailer Transactions (ALERT)', 'Total FY2021 Spending ($M)': '$5.949', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '3'}, 
    {'UII': '005-000000063', 'Bureau': 'Risk Management Agency', 'Investment Title': 'FPAC-RMA-13 Emerging Information Technology Architecture (EITA)', 'Total FY2021 Spending ($M)': '$16.468', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '31'}, 
    {'UII': '005-000000073', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-AgPRS - USDA Public Safety Land Mobile Radio System', 'Total FY2021 Spending ($M)': '$42.569', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '5'}, 
    {'UII': '005-000000185', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Certification, Accreditation, Registration, Permitting, and Other Licensing (CARPOL)', 'Total FY2021 Spending ($M)': '$16.427', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '4'}, 
    {'UII': '005-000000235', 'Bureau': 'Office of Chief Financial Officer', 'Investment Title': 'SO-OCFO-NFC-Payroll Services', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '14'}, 
    {'UII': '005-000001425', 'Bureau': 'Office of Chief Financial Officer', 'Investment Title': 'SO-OCFO-Financial Management Modernization Initiative (FMMI)', 'Total FY2021 Spending ($M)': '$121.330', 'Type': 'Major IT', 'CIO Rating': '5', '# of Projects': '15'}, 
    {'UII': '005-000001605', 'Bureau': 'Agricultural Marketing Service', 'Investment Title': 'MRP-AMS-Conformance Management', 'Total FY2021 Spending ($M)': '$20.851', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '6'}, 
    {'UII': '005-000001659', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Animal Disease Traceability Information System (ADTIS)', 'Total FY2021 Spending ($M)': '$4.354', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '7'}, 
    {'UII': '005-000001838', 'Bureau': 'Rural Development', 'Investment Title': 'RD-Enterprise Content Management (ECM)', 'Total FY2021 Spending ($M)': '$4.416', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '4'}, 
    {'UII': '005-000001870', 'Bureau': 'Farm Service Agency', 'Investment Title': 'FPAC-FSA-097 Farm Program Modernization (MIDAS)', 'Total FY2021 Spending ($M)': '$8.369', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '35'}, 
    {'UII': '005-000002148', 'Bureau': 'Food Safety and Inspection Service', 'Investment Title': 'FS-FSIS-Public Health Information System (PHIS)', 'Total FY2021 Spending ($M)': '$6.610', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '6'}, 
    {'UII': '005-000002223', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Natural Resource Manager (NRM)', 'Total FY2021 Spending ($M)': '$29.185', 'Type': 'Major IT', 'CIO Rating': '5', '# of Projects': '16'}, 
    {'UII': '005-000002376', 'Bureau': 'Natural Resources Conservation Service', 'Investment Title': 'FPAC-NRCS-Conservation Delivery Streamline Initiative (CDSI)', 'Total FY2021 Spending ($M)': '$2.672', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '6'}, 
    {'UII': '005-000002394', 'Bureau': 'Food and Nutrition Service', 'Investment Title': 'FNCS-FNS-Supplemental Nutrition Assistance Program (SNAP) Support', 'Total FY2021 Spending ($M)': '$9.289', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '9'}, 
    {'UII': '005-000003010', 'Bureau': 'Office of Chief Financial Officer', 'Investment Title': 'SO-OCFO-FSSP-Pegasys', 'Total FY2021 Spending ($M)': '$33.380', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '5'}, 
    {'UII': '005-000003190', 'Bureau': 'Office of Chief Financial Officer', 'Investment Title': 'SO-OCFO-NFC-Human Capital Management Services', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '3'}, 
    {'UII': '005-000003195', 'Bureau': 'Office of Chief Financial Officer', 'Investment Title': 'SO-OCFO-NFC-Employee Services', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '5'}, 
    {'UII': '005-000003220', 'Bureau': 'Foreign Agricultural Service', 'Investment Title': 'TFAA-FAS-IMART', 'Total FY2021 Spending ($M)': '$3.639', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '6'}, 
    {'UII': '005-000003240', 'Bureau': 'Executive Operations', 'Investment Title': 'DA-OES-Correspondence Management System (CMS)', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '1', '# of Projects': '3'}, 
    {'UII': '005-000003245', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Interagency Resource Ordering Capability (IROC)', 'Total FY2021 Spending ($M)': '$2.673', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '2'}, 
    {'UII': '005-000003255', 'Bureau': 'Office of the Secretary', 'Investment Title': 'DA-OO-Emergency Response', 'Total FY2021 Spending ($M)': '$0.321', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '3'}, 
    {'UII': '005-000003272', 'Bureau': 'Farm Service Agency', 'Investment Title': 'FPAC-FSA-125 Farm Programs', 'Total FY2021 Spending ($M)': '$25.521', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '21'}, 
    {'UII': '005-000003273', 'Bureau': 'Farm Service Agency', 'Investment Title': 'FPAC-FSA-126 Farm Loan Programs', 'Total FY2021 Spending ($M)': '$43.220', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '13'}, 
    {'UII': '005-000003276', 'Bureau': 'Farm Service Agency', 'Investment Title': 'FPAC-FSA-129 Program Financial Services', 'Total FY2021 Spending ($M)': '$18.878', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '13'}, 
    {'UII': '005-000003297', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Open Forest (FS Enterprise ePermit)', 'Total FY2021 Spending ($M)': '$2.000', 'Type': 'Major IT', 'CIO Rating': '2', '# of Projects': '1'}, 
    {'UII': '005-000003310', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-National Bio Agro Defense Facility (NBAF)', 'Total FY2021 Spending ($M)': '$14.650', 'Type': 'Major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000003311', 'Bureau': 'Farm Production and Conservation Business Center', 'Investment Title': 'FPAC-FBC-1001 Customer Engagement and Management Services', 'Total FY2021 Spending ($M)': '$26.475', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '12'}, 
    {'UII': '005-000003325', 'Bureau': 'Farm Service Agency', 'Investment Title': 'FPAC-FSA-127 Geospatial Services', 'Total FY2021 Spending ($M)': '$47.745', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '10'}, 
    {'UII': '005-000003326', 'Bureau': 'Office of the Secretary', 'Investment Title': 'DA-OCX-Contact Center', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '2'}, 
    {'UII': '005-000003327', 'Bureau': 'Office of Chief Information Officer', 'Investment Title': 'SO-OCIO-DISC-Robotics Process Automation (RPA)', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '7'}, 
    {'UII': '005-000003328', 'Bureau': 'Office of Chief Information Officer', 'Investment Title': 'SO-OCIO-Enterprise Data Analytics Platform and Toolset (EDAPT)', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '2', '# of Projects': '1'}, 
    {'UII': '005-000003353', 'Bureau': 'Office of the Secretary', 'Investment Title': 'DA-OCX-Customer Experience', 'Total FY2021 Spending ($M)': '$0.300', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '3'}, 
    {'UII': '005-000003355', 'Bureau': 'Office of the General Counsel', 'Investment Title': 'SO-OGC-FOIAXpress', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '2'}, 
    {'UII': '005-000003400', 'Bureau': 'Foreign Agricultural Service', 'Investment Title': 'TFAA-FAS-Overseas Operations', 'Total FY2021 Spending ($M)': '$0.918', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '2'}, 
    {'UII': '005-000003410', 'Bureau': 'Rural Development', 'Investment Title': 'RD-Residential Loans, Grants & Guarantees (RLGG)', 'Total FY2021 Spending ($M)': '$10.963', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '6'}, 
    {'UII': '005-000003415', 'Bureau': 'Rural Development', 'Investment Title': 'RD-Commercial Loans, Grants & Guarantees (CLGG)', 'Total FY2021 Spending ($M)': '$21.198', 'Type': 'Major IT', 'CIO Rating': '3', '# of Projects': '22'}, 
    {'UII': '005-000003435', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Mission Support Services', 'Total FY2021 Spending ($M)': '$48.711', 'Type': 'Major IT', 'CIO Rating': '1', '# of Projects': '2'}, 
    {'UII': '005-000003440', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Wildland Fire & Aviation Management', 'Total FY2021 Spending ($M)': '$38.700', 'Type': 'Major IT', 'CIO Rating': '4', '# of Projects': '5'}, 
    {'UII': '005-999990010', 'Bureau': 'Forest Service', 'Investment Title': 'NRE-FS-Recreation.gov', 'Total FY2021 Spending ($M)': '$0.001', 'Type': 'Major IT', 'CIO Rating': '1', '# of Projects': '2'}, 
    {'UII': '005-000000027', 'Bureau': 'Food and Nutrition Service', 'Investment Title': 'FNCS-FNS-Store Tracking and Redemption System (STARS)', 'Total FY2021 Spending ($M)': '$8.976', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000045', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-MIS 2000', 'Total FY2021 Spending ($M)': '$7.319', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000047', 'Bureau': 'Food and Nutrition Service', 'Investment Title': 'FNCS-FNS-Financial Management Support System (FMSS)', 'Total FY2021 Spending ($M)': '$5.133', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000074', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-VS Laboratory and Regulatory Applications (VSLRA)', 'Total FY2021 Spending ($M)': '$3.858', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000097', 'Bureau': 'Office of Civil Rights', 'Investment Title': 'SO-OASCR-Office of the Assistant Secretary for Civil Rights', 'Total FY2021 Spending ($M)': '$0.297', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000160', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Emergency Management Response Services 2.0 (EMRS-2)', 'Total FY2021 Spending ($M)': '$1.429', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000187', 'Bureau': 'Office of the Secretary', 'Investment Title': 'DA-OHRM-OneUSDA Human Resources Enterprise Solution Project', 'Total FY2021 Spending ($M)': '$0.000', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000236', 'Bureau': 'Food Safety and Inspection Service', 'Investment Title': 'FS-FSIS-Laboratory General Support System (Lab GSS)', 'Total FY2021 Spending ($M)': '$3.272', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000000276', 'Bureau': 'Agricultural Research Service', 'Investment Title': 'REE-ARS-Application Standard Investment', 'Total FY2021 Spending ($M)': '$45.601', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000001405', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Phytosanitary Certificate Issuance and Tracking System (PCIT)', 'Total FY2021 Spending ($M)': '$4.458', 'Type': 'Non-major IT', 'CIO Rating': '3', '# of Projects': '--'}, 
    {'UII': '005-000001606', 'Bureau': 'Agricultural Marketing Service', 'Investment Title': 'MRP-AMS-Public Good IT Investments', 'Total FY2021 Spending ($M)': '$4.431', 'Type': 'Non-major IT', 'CIO Rating': '2', '# of Projects': '--'}, 
    {'UII': '005-000001786', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Veterinary Services Process Streamlining (VSPS)', 'Total FY2021 Spending ($M)': '$1.497', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000001822', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Electronic Permits System (ePermits)', 'Total FY2021 Spending ($M)': '$2.208', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}, 
    {'UII': '005-000001861', 'Bureau': 'Animal and Plant Health Inspection Service', 'Investment Title': 'MRP-APHIS-Agricultural Quarantine Activity System (AQAS)', 'Total FY2021 Spending ($M)': '$1.082', 'Type': 'Non-major IT', 'CIO Rating': '--', '# of Projects': '--'}
    ]


data_from_pdf = [
    {'Name of this Investment': 'FNCS-FNS-Anti-Fraud Locator Using EBT Retailer Transactions (ALERT)', 'Unique Investment Identifier (UII)': '005-000000042'}, 
    {'Name of this Investment': 'MRP-AMS-Conformance Management', 'Unique Investment Identifier (UII)': '005-000001605'}, 
    {'Name of this Investment': 'SO-OCFO-FSSP-Pegasys', 'Unique Investment Identifier (UII)': '005-000003010'}, 
    {'Name of this Investment': 'MRP-APHIS-Certification, Accreditation, Registration, Permitting, and Other\nLicensing (CARPOL)', 'Unique Investment Identifier (UII)': '005-000000185'}, 
    {'Name of this Investment': 'NRE-FS-Natural Resource Manager (NRM)', 'Unique Investment Identifier (UII)': '005-000002223'}, 
    {'Name of this Investment': 'FNCS-FNS-Supplemental Nutrition Assistance Program (SNAP) Support', 'Unique Investment Identifier (UII)': '005-000002394'}, 
    {'Name of this Investment': 'MRP-AMS-Web-Based Supply Chain Management (WBSCM)', 'Unique Investment Identifier (UII)': '005-000000018'}, 
    {'Name of this Investment': 'FPAC-FSA-129 Program Financial Services', 'Unique Investment Identifier (UII)': '005-000003276'}, 
    {'Name of this Investment': 'FPAC-FSA-125 Farm Programs', 'Unique Investment Identifier (UII)': '005-000003272'}, 
    {'Name of this Investment': 'SO-OCIO-DISC-AgLearn', 'Unique Investment Identifier (UII)': '005-000000035'}, 
    {'Name of this Investment': 'FPAC-FSA-126 Farm Loan Programs', 'Unique Investment Identifier (UII)': '005-000003273'}, 
    {'Name of this Investment': 'FPAC-FBC-1001 Customer Engagement and Management Services', 'Unique Investment Identifier (UII)': '005-000003311'}, 
    {'Name of this Investment': 'MRP-APHIS-Animal Disease Traceability Information System (ADTIS)', 'Unique Investment Identifier (UII)': '005-000001659'}, 
    {'Name of this Investment': 'SO-OCFO-NFC-Payroll Services', 'Unique Investment Identifier (UII)': '005-000000235'},
    {'Name of this Investment': 'NRE-FS-Open Forest (FS Enterprise ePermit)', 'Unique Investment Identifier (UII)': '005-000003297'},
    {'Name of this Investment': 'DA-OES-Correspondence Management System (CMS)', 'Unique Investment Identifier (UII)': '005-000003240'},
    {'Name of this Investment': 'FPAC-NRCS-Conservation Delivery Streamline Initiative (CDSI)', 'Unique Investment Identifier (UII)': '005-000002376'},
    {'Name of this Investment': 'FPAC-FSA-097 Farm Program Modernization (MIDAS)', 'Unique Investment Identifier (UII)': '005-000001870'},
    {'Name of this Investment': 'FS-FSIS-Public Health Information System (PHIS)', 'Unique Investment Identifier (UII)': '005-000002148'},
    {'Name of this Investment': 'DA-OCP-Integrated Acquisition System (IAS)', 'Unique Investment Identifier (UII)': '005-000000039'},
    {'Name of this Investment': 'NRE-FS-Interagency Resource Ordering Capability (IROC)', 'Unique Investment Identifier (UII)': '005-000003245'},
    {'Name of this Investment': 'RD-Enterprise Content Management (ECM)', 'Unique Investment Identifier (UII)': '005-000001838'},
    {'Name of this Investment': 'TFAA-FAS-IMART', 'Unique Investment Identifier (UII)': '005-000003220'},
    {'Name of this Investment': 'NRE-FS-AgPRS - USDA Public Safety Land Mobile Radio System', 'Unique Investment Identifier (UII)': '005-000000073'},
    {'Name of this Investment': 'SO-OCFO-NFC-Employee Services', 'Unique Investment Identifier (UII)': '005-000003195'},
    {'Name of this Investment': 'FPAC-RMA-13 Emerging Information Technology Architecture (EITA)', 'Unique Investment Identifier (UII)': '005-000000063'},
    {'Name of this Investment': 'SO-OCFO-NFC-Human Capital Management Services', 'Unique Investment Identifier (UII)': '005-000003190'},
    {'Name of this Investment': 'SO-OCFO-Financial Management Modernization Initiative (FMMI)', 'Unique Investment Identifier (UII)': '005-000001425'},
    ]